---
layout: page
title: Past Global Change FAIROS Research Coordination Network
description: Implementing FAIR and CARE principles in the historical sciences
---
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

