---
theme: jekyll-theme-minimal
layout: page
title: Past Global Change FAIROS Research Coordination Network
description: Implementing FAIR and CARE principles in the historical sciences
email: "globalchangefairos@gmail.com"
logo: "/images/fairos-logo-transp.png"
team_members:
  -
    name: "Jessica Blois"
    role: "Principal Investigator"
    institution: "University of California, Merced"
    picture: "\"./images/blois_headshot.jpg\""
  -
    name: "Suzanne Pilaar Birch"
    role: "Co-Principal Investigator"
    institution: "University of Florida"
    picture: "\"./images/birch_headshot.jpg\""
  -
    name: "Meghan Balk"
    role: "Co-Principal Investigator"
    institution: "University of Arizona"
    picture: "\"./images/balk_headshot.jpg\""
  -
    name: "Simon Goring"
    role: "Co-Principal Investigator"
    institution: "University of Wisconsin, Madison"
    picture: "\"./images/goring_headshot.jpg\""
  -
    name: "John W. Williams"
    role: "Co-Principal Investigator"
    institution: "University of Wisconsin, Madison"
    picture: "\"./images/williams_headshot.jpg\""
  -
    name: "Kitty Emery"
    role: "Co-Principal Investigator"
    institution: "University of Florida"   
    picture: "\"./images/emery_headshot.jpg\""
  -
    name: "Leigh Lieberman"
    role: "Co-Principal Investigator"
    institution: "Open Context"
    picture: "\"./images/emery_headshot.jpg\""
  -
    name: "Andrea Thomer"
    role: "Co-Principal Investigator"
    institution: "University of Arizona"
    picture: "\"./images/emery_headshot.jpg\""
  -
    name: "Michelle LeFebvre"
    role: "Co-Principal Investigator"
    institution: "University of Florida"
    picture: "\"./images/emery_headshot.jpg\""
---
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      
  

